-- MySQL Script generated by MySQL Workbench
-- Mon Jul 30 16:27:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema personal_finance_app
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `personal_finance_app` ;

-- -----------------------------------------------------
-- Schema personal_finance_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `personal_finance_app` DEFAULT CHARACTER SET utf8 ;
USE `personal_finance_app` ;

-- -----------------------------------------------------
-- Table `personal_finance_app`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `personal_finance_app`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `role` VARCHAR(45) NOT NULL DEFAULT 'standard',
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `personal_finance_app`.`expense_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `personal_finance_app`.`expense_category` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `personal_finance_app`.`budget`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `personal_finance_app`.`budget` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `category_id` INT(11) NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_budget_user_idx` (`user_id` ASC),
  INDEX `fk_expense_category_budget_idx` (`category_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `personal_finance_app`.`expense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `personal_finance_app`.`expense` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,2) NOT NULL,
  `category_id` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_expense_user_idx` (`user_id` ASC),
  INDEX `fk_expense_category_expense_idx` (`category_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `personal_finance_app`.`future_expense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `personal_finance_app`.`future_expense` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `category_id` INT(11) NOT NULL,
  `amount` VARCHAR(45) NOT NULL,
  `date_expected` DATE NOT NULL,
  `recurring` TINYINT(1) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_future_expense_user_idx` (`user_id` ASC),
  INDEX `fk_future_expense_expense_category_idx` (`category_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `personal_finance_app`.`income_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `personal_finance_app`.`income_category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `personal_finance_app`.`income`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `personal_finance_app`.`income` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `category_id` INT(11) NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `date_received` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_income_user_idx` (`user_id` ASC),
  INDEX `fk_income_categories_income_idx` (`category_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `personal_finance_app`.`income_stream`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `personal_finance_app`.`income_stream` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `category_id` INT(11) NOT NULL,
  `expected_amount` DECIMAL(10,2) NOT NULL,
  `start_date` DATE NOT NULL,
  `recurrences_per_year` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_income_stream_user_idx` (`user_id` ASC),
  INDEX `fk_income_stream_income_categories_idx` (`category_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE USER 'user' IDENTIFIED BY 'user';

GRANT SELECT ON TABLE `personal_finance_app`.* TO 'user';
GRANT SELECT, INSERT, TRIGGER ON TABLE `personal_finance_app`.* TO 'user';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `personal_finance_app`.* TO 'user';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
